name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Decrypt large secret
        run: ./.github/scripts/ds.sh
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.KEY_PASS }}
      - name: Build with Gradle
        run: ./gradlew build
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false

